apiVersion: v1
kind: ReplicationController
metadata:
  name: tomcat
  namespace: testgroup
spec:
  replicas: 2
  selector:
    app: tomcat
  template:
    metadata:
     labels:
      app: tomcat
    spec:
     containers:
     - name: tomcat
       image: kubeguide/tomcat-app:v1
       ports:
       - containerPort: 8080
