- name: Unarchive a file that is already on the remote machine
  unarchive:
    src: /home/ipnet/sgw/jdk-8u31-linux-x64.tar.gz
    dest: "/home/{{ user }}/"
    remote_src: no
    owner: "{{ user }}"
    group: "{{ user }}"
- name: set env for jdk
  template:
    src: setjdk.j2 
    dest: "/home/{{ user }}/.bash_profile"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0644
    backup: yes
- name: source
#  shell: /bin/echo "{{ item }}" >> /home/{{ user }}/.bash_profile; 
  shell: sh -lc "source /home/{{ user }}/.bash_profile"
#  with_items:
#     - export JAVA_HOME=/home/ipnet/jdk1.8.0_31
#     - export PATH=$JAVA_HOME/bin:$PATH
#     - export export CLASS_PATH=.:$JAVA_HOME/lib
